---
verifier:
  name: inspec

suites:
  - name: default
    run_list:
       - recipe[osl-scponly]
  - name: _scponly
    run_list:
      - recipe[osl-scponly]
      - recipe[scponly-test::scponly]
  - name: _scponly-chroot
    run_list:
      - recipe[osl-scponly]
      - recipe[scponly-test::scponly-chroot]
