name             'osl-scponly'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
source_url       'https://github.com/osuosl-cookbooks/osl-scponly'
issues_url       'https://github.com/osuosl-cookbooks/osl-scponly/issues'
license          'Apache-2.0'
chef_version     '>= 14.0'
description      'Installs/Configures osl-scponly'
version          '1.3.0'

supports         'centos', '~> 7.0'
supports         'centos', '~> 8.0'

depends          'line'
depends          'osl-repos'
