name             'osl-scponly'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
source_url       'https://github.com/osuosl-cookbooks/osl-scponly'
issues_url       'https://github.com/osuosl-cookbooks/osl-scponly/issues'
license          'Apache-2.0'
chef_version     '>= 16.0'
description      'Installs/Configures osl-scponly'
version          '1.6.1'

supports         'almalinux', '~> 8.0'
supports         'almalinux', '~> 9.0'

depends          'line'
depends          'osl-repos'
depends          'osl-selinux'
depends          'yum-osuosl'
